// generated by "sampctl package generate"

#include "progress-key.inc"

main() 
{
	// write tests for libraries here and run "sampctl package run"
}

public OnPlayerSpawn(playerid)
{
	Progress_Show(playerid, 20, PROGRESS_TEST, "Progress Title");
	return 1;
}

Progress:PROGRESS_TEST(playerid, success)
{
	if (success) {}
		print("success");
	}
	else {
		print("fail");
	}
	return 1;
}